version: '3.8'

services:
  api:
    build: /api
    container_name: api
    ports:
      - 3000:3000

  web:
    build: /web
    container_name: web
    ports:
      - 80:80

  db:
    image: mongo
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - data:/data
    ports:
      - "27017:27017"

  db-admin:
    image: mongo-express
    container_name: db_admin
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_URL="mongodb://root:admin@db:27017"

volumes:
  data: {}

networks:
  default:
    name: mongodb_network 